sndcp: Fix missing dep link against libmath
It is already present in libosmo-gprs-sndcp.pc.in Libs.private, but it
was forgotten at compile time.
That makes it fail under some systems when linking against it (like jenkins):
/build/deps/install/stow/libosmo-gprs/lib/libosmo-gprs-sndcp.so: undefined reference to `ceil'

Change-Id: Iba9629b323b50b28cc4c54cf35b2e39ee89bc192